### ISSUE TITLE
Unable to connect to Fake Server

### ISSUE THREAD

**Issue by NiceDavid07115** [Dark-Night-Base/AutoSleep#2]
I am using Hibernate, but I have encountered a serious problem. When waitmin passed, Hibernate stopped the server, and the server also showed that the fake server started running. When I tried to ping the fake server in the game, it showed that it could not connect to the server. I made sure that my server was configured correctly. I also tested it on my Windows and Linux systems. The following is the server log:
最近在试试Hibernate这个插件，但是遇到了很严重的问题。开服10分钟过后Hibernate停了服，服务端也显示Fake server开始运行，不过在游戏中尝试刷新去连接到fake server却显示无法连接至服务器，直接连接服务器时fake server也没有监听到有人尝试连接。服务端配置应该是正确的。我也在我的Windows和Centos系统都测试过。以下是相关服务端日志截图：
![屏幕截图 2021-01-30 110125](https://user-images.githubusercontent.com/78246604/106348454-5fe6a400-6301-11eb-9cb8-dbd28aaa8026.png)
![屏幕截图 2021-01-30 110100](https://user-images.githubusercontent.com/78246604/106348463-6b39cf80-6301-11eb-8de0-9dedddfd0a43.png)
![image](https://user-images.githubusercontent.com/78246604/106348632-8b1dc300-6302-11eb-877c-eb57ae991ac9.png)
`[Server] [13:50:31] [Server thread/INFO]: Done (2.742s)! For help, type "help"
[MCDR] [13:51:33] [Thread-2/INFO]: Hibernate!
[Server] [13:51:33] [Server thread/INFO]: Stopping the server
[Server] [13:51:33] [Server thread/INFO]: Stopping server
[Server] [13:51:33] [Server thread/INFO]: Saving players
[Server] [13:51:33] [Server thread/INFO]: Saving worlds
[Server] [13:51:33] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[Server] [13:51:55] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [13:51:55] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[Server] [13:51:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [13:51:56] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[Server] [13:51:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[Server] [13:51:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[Server] [13:51:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[Server] [13:51:56] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[MCDR] [13:51:56] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [13:51:56] [Thread-3/INFO]: FakeServer start!
[MCDR] [13:51:56] [Thread-3/INFO]: FakeServer is ready
`
`[MCDR] [2021-01-30 10:47:21] [MainThread/INFO]: 语言已设置为 zh_cn
[MCDR] [2021-01-30 10:47:21] [MainThread/INFO]: 编码 / 解码方式已设置为 utf-8 / cp936
[MCDR] [2021-01-30 10:47:21] [MainThread/INFO]: 插件文件夹列表:
[MCDR] [2021-01-30 10:47:21] [MainThread/INFO]: - plugins
[MCDR] [2021-01-30 10:47:21] [MainThread/INFO]: 解析处理器已设置为 vanilla_handler
[MCDR] [2021-01-30 10:47:21] [TaskExecutor/INFO]: 刷新所有插件中
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/INFO]: 插件 crash_restart@1.0.0 已加载
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/INFO]: 插件 hibernate@0.0.1 已加载
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/WARNING]: Plugin ID of RegularPlugin[file=info.py,path=plugins\info.py,state=0] not found, use fallback id info instead
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/WARNING]: RegularPlugin[file=info.py,path=plugins\info.py,state=0] doesn't specific a version, use fallback version 0.0.0
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/INFO]: 插件 info@0.0.0 已加载
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/INFO]: 插件 quick_backup_multi@1.1.0 已加载
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/INFO]: 插件 simple_op@1.0.0 已加载
[MCDR] [2021-01-30 10:47:22] [TaskExecutor/INFO]: 共加载: §75§r 个插件; 已加载插件数: §76§r
[MCDR] [2021-01-30 10:47:22] [MainThread/INFO]: 正在启动服务端，启动参数为 "java -Xms1G -Xmx1G -jar fabric-server-launch.jar nogui"
[MCDR] [2021-01-30 10:47:22] [MainThread/INFO]: 服务端正在以 PID 8880 运行中
[MCDR] [2021-01-30 10:47:24] [CheckUpdate/INFO]: MCDR 已为最新版
[MCDR] [2021-01-30 10:57:42] [Thread-2/INFO]: Hibernate!
[MCDR] [2021-01-30 10:57:43] [MainThread/INFO]: 服务端进程返回代码: 0
[MCDR] [2021-01-30 10:57:43] [Thread-5/INFO]: FakeServer start!
[MCDR] [2021-01-30 10:57:43] [Thread-5/INFO]: FakeServer is ready
`
衷心希望你能解决这个问题，如需更多配置信息请联系我

**Comment by Youmiel** [comment]
Same issue for me.
我也遇到了相同的问题。

**Comment by ghost** [comment]
Same issue for me.
我也遇到了相同的问题。

**Comment by ghost** [comment]
我跳出來
Error in getResultNew: timed out
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "plugins\Hibernate.py", line 41, in query_playernum
    playerCount = Client().getResultNew()["OnlinePlayers"]
  File "plugins\Hibernate.py", line 218, in getResultNew
    server_property["Protocol"] = status["Protocol"]
KeyError: 'Protocol'
求解

**Comment by zhr1502** [comment]
The same problem,fakeserver cannot be detected on the client
一样的问题，在客户端检测不到fakeserver

**Comment by ghost** [comment]
我也是一样我问题

**Comment by keaizhu** [comment]
相同的问题

**Comment by Sciroccogti** [comment]
请尝试一下 https://github.com/HIM049/MCDR_HibernateR 看看是否能够正常使用
